-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.4 and Filter Design HDL Coder 3.1.3.
-- Generated on: 2020-08-19 17:05:14
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: C:\Users\Kal\Desktop\BANDPASS\Last
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 16
-- Stable            : Yes
-- Linear Phase      : Yes (Type 2)
-- Arithmetic        : fixed
-- Numerator         : s8,9 -> [-2.500000e-01 2.500000e-01)
-- Input             : s8,7 -> [-1 1)
-- Filter Internals  : Specify Precision
--   Output          : s16,15 -> [-1 1)
--   Product         : s16,15 -> [-1 1)
--   Accumulator     : s18,16 -> [-2 2)
--   Round Mode      : floor
--   Overflow Mode   : saturate
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(7 DOWNTO 0); -- sfix8_En7
         filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  --TYPE delay_pipeline_type IS ARRAY (15 downto 0) OF signed(7 DOWNTO 0); -- sfix8_En7
--type delay_pipeline_type is (E0,E1,E2,E3,E4,E5,E6,E7);
--signal coeff1,coeff2,coeff3,coeff4,coeff5,coeff6,coeff7,coeff8,coeff9,coeff10,coeff11,coeff12,coeff13,coeff14,coeff15,coeff16: SIGNED (16 DOWNTO 1);

signal delay_pipeline_type_0 :signed(15 downto 0);
signal delay_pipeline_type_1 :signed(15 downto 0);
signal delay_pipeline_type_2 :signed(15 downto 0);
signal delay_pipeline_type_3 :signed(15 downto 0);
signal delay_pipeline_type_4 :signed(15 downto 0);
signal delay_pipeline_type_5 :signed(15 downto 0);
  signal delay_pipeline_type_6 :signed(15 downto 0);
signal delay_pipeline_type_7 :signed(15 downto 0);
signal delay_pipeline_type_8 :signed(15 downto 0);
  signal delay_pipeline_type_9 :signed(15 downto 0);
signal delay_pipeline_type_10 :signed(15 downto 0);
signal delay_pipeline_type_11 :signed(15 downto 0);
signal delay_pipeline_type_12 :signed(15 downto 0);
signal delay_pipeline_type_13 :signed(15 downto 0);
signal delay_pipeline_type_14 :signed(15 downto 0);
signal delay_pipeline_type_15 :signed(15 downto 0);

  
  
  
  
  -- Signals
  
  SIGNAL product16                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp                         : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product15                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_1                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product14                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL product13                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL product12                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL product11                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_2                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product10                        : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_3                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product9                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_4                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product8                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_5                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product7                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_6                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product6                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_7                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product5                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL product4                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL product3                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL product2                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_8                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product1_cast                    : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL product1                         : signed(12 DOWNTO 0); -- sfix13_En14
  SIGNAL mul_temp_9                       : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL sum1                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp                         : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum2                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_1                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum3                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_2                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum4                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_3                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum5                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_4                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum6                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_5                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum7                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_6                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum8                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_7                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum9                             : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_8                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum10                            : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_9                       : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum11                            : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_10                      : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum12                            : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_11                      : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum13                            : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_12                      : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum14                            : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_13                      : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL sum15                            : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL add_temp_14                      : signed(16 DOWNTO 0); -- sfix17_En14
  SIGNAL output_typeconvert               : signed(15 DOWNTO 0); -- sfix16_En14
  SIGNAL output_register                  : signed(15 DOWNTO 0); -- sfix16_En14

SIGNAL coeff1: signed(7 downto 0);
SIGNAL coeff2: signed(7 downto 0);
signal coeff3 :signed(7 downto 0);
signal coeff4 :signed(7 downto 0);
signal coeff5 :signed(7 downto 0);
SIGNAL coeff6: signed(7 downto 0);
SIGNAL coeff7: signed(7 downto 0);
signal coeff8 :signed(7 downto 0);
signal coeff9 :signed(7 downto 0);
signal coeff10 :signed(7 downto 0);
SIGNAL coeff11 : signed(7 downto 0);
SIGNAL coeff12 : signed(7 downto 0);
signal coeff13 :signed(7 downto 0);
signal coeff14 :signed(7 downto 0);
signal coeff15 :signed(7 downto 0);
signal coeff16 :signed(7 downto 0);

begin
coeff1(7 downto 0)<=to_signed(18, 8); -- sfix8_En9
coeff2(7 downto 0)<=to_signed(-27, 8); -- sfix8_En9
coeff3(7 downto 0)<=to_signed(-36, 8); -- sfix8_En9
coeff4(7 downto 0)<=to_signed(44, 8); -- sfix8_En9
coeff5(7 downto 0)<=to_signed(52, 8); -- sfix8_En9
coeff6(7 downto 0)<=to_signed(-58, 8); -- sfix8_En9
coeff7(7 downto 0)<=to_signed(-62, 8); -- sfix8_En9
coeff8(7 downto 0)<=to_signed(65, 8); -- sfix8_En9
coeff9(7 downto 0)<=to_signed(65, 8); -- sfix8_En9
coeff10(7 downto 0)<=to_signed(-62, 8); -- sfix8_En9
coeff11(7 downto 0)<=to_signed(-58, 8); -- sfix8_En9
coeff12(7 downto 0)<=to_signed(52, 8); -- sfix8_En9
coeff13(7 downto 0)<=to_signed(44, 8); -- sfix8_En9
coeff14(7 downto 0)<=to_signed(-36, 8); -- sfix8_En9
coeff15(7 downto 0)<=to_signed(-27, 8); -- sfix8_En9
coeff16(7 downto 0)<=to_signed(18, 8); -- sfix8_En9
  



  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk)
  
    
  ----------------------------------------------------------  
  VARIABLE mul_a1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_a8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_a12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_a34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_a56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_a78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add1, add2   : Std_Logic_Vector(11 downto 0);

  ----------------------------------------------------------  
  VARIABLE mul_b1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_b8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_b12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_b34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_b56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_b78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add3, add4   : Std_Logic_Vector(11 downto 0);

   ----------------------------------------------------------  
  VARIABLE mul_c1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_c8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_c12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_c34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_c56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_c78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add5, add6   : Std_Logic_Vector(11 downto 0);

  ----------------------------------------------------------  
  VARIABLE mul_d1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_d8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_d12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_d34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_d56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_d78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add7, add8   : Std_Logic_Vector(11 downto 0);
   -----------------------------------------------------------
   ----------------------------------------------------------  
  VARIABLE mul_e1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_e8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_e12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_e34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_e56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_e78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add9, add10   : Std_Logic_Vector(11 downto 0);
-----------------------------------------------------------
  ----------------------------------------------------------  
  VARIABLE mul_f1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_f8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_f12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_f34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_f56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_f78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add11, add12   : Std_Logic_Vector(11 downto 0);
-----------------------------------------------------------
 ----------------------------------------------------------  
  VARIABLE mul_g1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_g8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_g12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_g34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_g56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_g78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add13, add14   : Std_Logic_Vector(11 downto 0);
-----------------------------------------------------------
 ----------------------------------------------------------  
  VARIABLE mul_h1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_h8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_h12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_h34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_h56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_h78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add15, add16   : Std_Logic_Vector(11 downto 0);
-----------------------------------------------------------
 ----------------------------------------------------------  
  VARIABLE mul_i1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_i8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_i12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_i34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_i56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_i78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add17, add18   : Std_Logic_Vector(11 downto 0);
-----------------------------------------------------------
 ----------------------------------------------------------  
  VARIABLE mul_j1 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j2 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j3 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j4 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j5 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j6 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j7 : Std_Logic_Vector(8 downto 0);
  VARIABLE mul_j8 : Std_Logic_Vector(8 downto 0);
  
  VARIABLE mul_j12 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_j34 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_j56 : Std_Logic_Vector(9 downto 0);
  VARIABLE mul_j78 : Std_Logic_Vector(9 downto 0);

  VARIABLE add19, add20   : Std_Logic_Vector(11 downto 0);
-----------------------------------------------------------
-----------------------------------------------------------
BEGIN
   if Clk'event and Clk='1' then

----------------------------------------------------------
      mul_a1(0) := delay_pipeline_type_15(0) and  coeff16(0);
   mul_a1(1) := delay_pipeline_type_15(0) and  coeff16(1);
   mul_a1(2) := delay_pipeline_type_15(0) and  coeff16(2);
   mul_a1(3) := delay_pipeline_type_15(0) and  coeff16(3);
   mul_a1(4) := delay_pipeline_type_15(0) and  coeff16(4);
   mul_a1(5) := delay_pipeline_type_15(0) and  coeff16(5);
   mul_a1(6) := delay_pipeline_type_15(0) and  coeff16(6);
   mul_a1(7) := delay_pipeline_type_15(0) and  coeff16(7);
   mul_a1(8) := '0';

   mul_a2(0) := '0';
   mul_a2(1) := delay_pipeline_type_15(1) and coeff16(0);
   mul_a2(2) := delay_pipeline_type_15(1) and coeff16(1);
   mul_a2(3) := delay_pipeline_type_15(1) and coeff16(2);
   mul_a2(4) := delay_pipeline_type_15(1) and coeff16(3);
   mul_a2(5) := delay_pipeline_type_15(1) and coeff16(4);
   mul_a2(6) := delay_pipeline_type_15(1) and coeff16(5);
   mul_a2(7) := delay_pipeline_type_15(1) and coeff16(6);
   mul_a2(8) := delay_pipeline_type_15(1) and coeff16(7);
   
   mul_a3(0) := delay_pipeline_type_15(2) and coeff16(0);
   mul_a3(1) := delay_pipeline_type_15(2) and coeff16(1);
   mul_a3(2) := delay_pipeline_type_15(2) and coeff16(2);
   mul_a3(3) := delay_pipeline_type_15(2) and coeff16(3);
   mul_a3(4) := delay_pipeline_type_15(2) and coeff16(4);
   mul_a3(5) := delay_pipeline_type_15(2) and coeff16(5);
   mul_a3(6) := delay_pipeline_type_15(2) and coeff16(6);
   mul_a3(7) := delay_pipeline_type_15(2) and coeff16(7);
   mul_a3(8) := '0';
   
   mul_a4(0) := '0';
   mul_a4(1) := delay_pipeline_type_15(3) and coeff16(0);
   mul_a4(2) := delay_pipeline_type_15(3) and coeff16(1);
   mul_a4(3) := delay_pipeline_type_15(3) and coeff16(2);
   mul_a4(4) := delay_pipeline_type_15(3) and coeff16(3);
   mul_a4(5) := delay_pipeline_type_15(3) and coeff16(4);
   mul_a4(6) := delay_pipeline_type_15(3) and coeff16(5);
   mul_a4(7) := delay_pipeline_type_15(3) and coeff16(6);
   mul_a4(8) := delay_pipeline_type_15(3) and coeff16(7);

      

   
   mul_a5(0) := delay_pipeline_type_15(4) and coeff16(0);
   mul_a5(1) := delay_pipeline_type_15(4) and coeff16(1);
   mul_a5(2) := delay_pipeline_type_15(4) and coeff16(2);
   mul_a5(3) := delay_pipeline_type_15(4) and coeff16(3);
   mul_a5(4) := delay_pipeline_type_15(4) and coeff16(4);
   mul_a5(5) := delay_pipeline_type_15(4) and coeff16(5);
   mul_a5(6) := delay_pipeline_type_15(4) and coeff16(6);
   mul_a5(7) := delay_pipeline_type_15(4) and coeff16(7);
   mul_a5(8) := '0';

   mul_a6(0) := '0';
   mul_a6(1) := delay_pipeline_type_15(5) and coeff16(0);
   mul_a6(2) := delay_pipeline_type_15(5) and coeff16(1);
   mul_a6(3) := delay_pipeline_type_15(5) and coeff16(2);
   mul_a6(4) := delay_pipeline_type_15(5) and coeff16(3);
   mul_a6(5) := delay_pipeline_type_15(5) and coeff16(4);
   mul_a6(6) := delay_pipeline_type_15(5) and coeff16(5);
   mul_a6(7) := delay_pipeline_type_15(5) and coeff16(6);
   mul_a6(8) := delay_pipeline_type_15(5) and coeff16(7);

   mul_a7(0) := delay_pipeline_type_15(6) and coeff16(0);
   mul_a7(1) := delay_pipeline_type_15(6) and coeff16(1);
   mul_a7(2) := delay_pipeline_type_15(6) and coeff16(2);
   mul_a7(3) := delay_pipeline_type_15(6) and coeff16(3);
   mul_a7(4) := delay_pipeline_type_15(6) and coeff16(4);
   mul_a7(5) :=delay_pipeline_type_15(6) and coeff16(5);
   mul_a7(6) := delay_pipeline_type_15(6) and coeff16(6);
   mul_a7(7) := delay_pipeline_type_15(6) and coeff16(7);
   mul_a7(8) := '0';

   mul_a8(0) := '0';
   mul_a8(1) := delay_pipeline_type_15(7) and coeff16(0);
   mul_a8(2) := delay_pipeline_type_15(7) and coeff16(1);
   mul_a8(3) := delay_pipeline_type_15(7) and coeff16(2);
   mul_a8(4) := delay_pipeline_type_15(7) and coeff16(3);
   mul_a8(5) := delay_pipeline_type_15(7) and coeff16(4);
   mul_a8(6) := delay_pipeline_type_15(7) and coeff16(5);
   mul_a8(7) := delay_pipeline_type_15(7) and coeff16(6);
   mul_a8(8) := delay_pipeline_type_15(7) and coeff16(7);


   mul_a12 := mul_a1 + mul_a2;
   mul_a34 := mul_a3 + mul_a4;
   mul_a56 := mul_a5 + mul_a6;
   mul_a78 := mul_a7 + mul_a8;

   add1 := ("00" & mul_a12) + (mul_a34 & "00");
   add2 := ("00" & mul_a56) + (mul_a78 & "00");
 

-----------------------------------------------------------
  mul_temp <= add1 + add2;
  product16 <= mul_temp(12 DOWNTO 0);

-----------------------------------------------------------

     mul_b1(0) := delay_pipeline_type_14(0) and  coeff15(0);
   mul_b1(1) := delay_pipeline_type_14(0) and  coeff15(1);
   mul_b1(2) := delay_pipeline_type_14(0) and  coeff15(2);
   mul_b1(3) := delay_pipeline_type_14(0) and  coeff15(3);
   mul_b1(4) := delay_pipeline_type_14(0) and  coeff15(4);
   mul_b1(5) := delay_pipeline_type_14(0) and  coeff15(5);
   mul_b1(6) := delay_pipeline_type_14(0) and  coeff15(6);
   mul_b1(7) := delay_pipeline_type_14(0) and  coeff15(7);
   mul_b1(8) := '0';

   mul_b2(0) := '0';
   mul_b2(1) := delay_pipeline_type_14(1) and coeff15(0);
   mul_b2(2) := delay_pipeline_type_14(1) and coeff15(1);
   mul_b2(3) := delay_pipeline_type_14(1) and coeff15(2);
   mul_b2(4) := delay_pipeline_type_14(1) and coeff15(3);
   mul_b2(5) := delay_pipeline_type_14(1) and coeff15(4);
   mul_b2(6) := delay_pipeline_type_14(1) and coeff15(5);
   mul_b2(7) := delay_pipeline_type_14(1) and coeff15(6);
   mul_b2(8) := delay_pipeline_type_14(1) and coeff15(7);
   
   mul_b3(0) := delay_pipeline_type_14(2) and coeff15(0);
   mul_b3(1) := delay_pipeline_type_14(2) and coeff15(1);
   mul_b3(2) := delay_pipeline_type_14(2) and coeff15(2);
   mul_b3(3) := delay_pipeline_type_14(2) and coeff15(3);
   mul_b3(4) := delay_pipeline_type_14(2) and coeff15(4);
   mul_b3(5) := delay_pipeline_type_14(2) and coeff15(5);
   mul_b3(6) := delay_pipeline_type_14(2) and coeff15(6);
   mul_b3(7) := delay_pipeline_type_14(2) and coeff15(7);
   mul_b3(8) := '0';
   
   mul_b4(0) := '0';
   mul_b4(1) := delay_pipeline_type_14(3) and coeff15(0);
   mul_b4(2) := delay_pipeline_type_14(3) and coeff15(1);
   mul_b4(3) := delay_pipeline_type_14(3) and coeff15(2);
   mul_b4(4) := delay_pipeline_type_14(3) and coeff15(3);
   mul_b4(5) := delay_pipeline_type_14(3) and coeff15(4);
   mul_b4(6) := delay_pipeline_type_14(3) and coeff15(5);
   mul_b4(7) := delay_pipeline_type_14(3) and coeff15(6);
   mul_b4(8) := delay_pipeline_type_14(3) and coeff15(7);

      

   
   mul_b5(0) := delay_pipeline_type_14(4) and coeff15(0);
   mul_b5(1) := delay_pipeline_type_14(4) and coeff15(1);
   mul_b5(2) := delay_pipeline_type_14(4) and coeff15(2);
   mul_b5(3) := delay_pipeline_type_14(4) and coeff15(3);
   mul_b5(4) := delay_pipeline_type_14(4) and coeff15(4);
   mul_b5(5) := delay_pipeline_type_14(4) and coeff15(5);
   mul_b5(6) := delay_pipeline_type_14(4) and coeff15(6);
   mul_b5(7) := delay_pipeline_type_14(4) and coeff15(7);
   mul_b5(8) := '0';

   mul_b6(0) := '0';
   mul_b6(1) := delay_pipeline_type_14(5) and coeff15(0);
   mul_b6(2) := delay_pipeline_type_14(5) and coeff15(1);
   mul_b6(3) := delay_pipeline_type_14(5) and coeff15(2);
   mul_b6(4) := delay_pipeline_type_14(5) and coeff15(3);
   mul_b6(5) := delay_pipeline_type_14(5) and coeff15(4);
   mul_b6(6) := delay_pipeline_type_14(5) and coeff15(5);
   mul_b6(7) := delay_pipeline_type_14(5) and coeff15(6);
   mul_b6(8) := delay_pipeline_type_14(5) and coeff15(7);

   mul_b7(0) := delay_pipeline_type_14(6) and coeff15(0);
   mul_b7(1) := delay_pipeline_type_14(6) and coeff15(1);
   mul_b7(2) := delay_pipeline_type_14(6) and coeff15(2);
   mul_b7(3) := delay_pipeline_type_14(6) and coeff15(3);
   mul_b7(4) := delay_pipeline_type_14(6) and coeff15(4);
   mul_b7(5) := delay_pipeline_type_14(6) and coeff15(5);
   mul_b7(6) := delay_pipeline_type_14(6) and coeff15(6);
   mul_b7(7) := delay_pipeline_type_14(6) and coeff15(7);
   mul_b7(8) := '0';

   mul_b8(0) := '0';
   mul_b8(1) := delay_pipeline_type_14(7) and coeff15(0);
   mul_b8(2) := delay_pipeline_type_14(7) and coeff15(1);
   mul_b8(3) := delay_pipeline_type_14(7) and coeff15(2);
   mul_b8(4) := delay_pipeline_type_14(7) and coeff15(3);
   mul_b8(5) := delay_pipeline_type_14(7) and coeff15(4);
   mul_b8(6) := delay_pipeline_type_14(7) and coeff15(5);
   mul_b8(7) := delay_pipeline_type_14(7) and coeff15(6);
   mul_b8(8) := delay_pipeline_type_14(7) and coeff15(7);


   mul_b12 := mul_b1 + mul_b2;
   mul_b34 := mul_b3 + mul_b4;
   mul_b56 := mul_b5 + mul_b6;
   mul_b78 := mul_b7 + mul_b8;

   add3 := ("00" & mul_b12) + (mul_b34 & "00");
   add4 := ("00" & mul_b56) + (mul_b78 & "00");
 
-----------------------------------------------------------


  mul_temp_1 <= add3 + add4;
  product15 <= mul_temp_1(12 DOWNTO 0);
-----------------------------------------------------------
  product14 <= resize(delay_pipeline_type_13, 15);

  product13 <= resize(delay_pipeline_type_12(15 DOWNTO 0),15);

  product12 <= resize(delay_pipeline_type_11(15 DOWNTO 0) , 15);
-----------------------------------------------------------
   mul_c1(0) := delay_pipeline_type_10(0) and  coeff11(0);
   mul_c1(1) := delay_pipeline_type_10(0) and  coeff11(1);
   mul_c1(2) := delay_pipeline_type_10(0) and  coeff11(2);
   mul_c1(3) := delay_pipeline_type_10(0) and  coeff11(3);
   mul_c1(4) := delay_pipeline_type_10(0) and  coeff11(4);
   mul_c1(5) := delay_pipeline_type_10(0) and  coeff11(5);
   mul_c1(6) := delay_pipeline_type_10(0) and  coeff11(6);
   mul_c1(7) := delay_pipeline_type_10(0) and  coeff11(7);
   mul_c1(8) := '0';

   mul_c2(0) := '0';
   mul_c2(1) := delay_pipeline_type_10(1) and coeff11(0);
   mul_c2(2) := delay_pipeline_type_10(1) and coeff11(1);
   mul_c2(3) := delay_pipeline_type_10(1) and coeff11(2);
   mul_c2(4) := delay_pipeline_type_10(1) and coeff11(3);
   mul_c2(5) := delay_pipeline_type_10(1) and coeff11(4);
   mul_c2(6) := delay_pipeline_type_10(1) and coeff11(5);
   mul_c2(7) := delay_pipeline_type_10(1) and coeff11(6);
   mul_c2(8) := delay_pipeline_type_10(1) and coeff11(7);
   
   mul_c3(0) := delay_pipeline_type_10(2) and coeff11(0);
   mul_c3(1) := delay_pipeline_type_10(2) and coeff11(1);
   mul_c3(2) := delay_pipeline_type_10(2) and coeff11(2);
   mul_c3(3) := delay_pipeline_type_10(2) and coeff11(3);
   mul_c3(4) := delay_pipeline_type_10(2) and coeff11(4);
   mul_c3(5) := delay_pipeline_type_10(2) and coeff11(5);
   mul_c3(6) := delay_pipeline_type_10(2) and coeff11(6);
   mul_c3(7) := delay_pipeline_type_10(2) and coeff11(7);
   mul_c3(8) := '0';
   
   mul_c4(0) := '0';
   mul_c4(1) := delay_pipeline_type_10(3) and coeff11(0);
   mul_c4(2) := delay_pipeline_type_10(3) and coeff11(1);
   mul_c4(3) := delay_pipeline_type_10(3) and coeff11(2);
   mul_c4(4) := delay_pipeline_type_10(3) and coeff11(3);
   mul_c4(5) := delay_pipeline_type_10(3) and coeff11(4);
   mul_c4(6) := delay_pipeline_type_10(3) and coeff11(5);
   mul_c4(7) := delay_pipeline_type_10(3) and coeff11(6);
   mul_c4(8) := delay_pipeline_type_10(3) and coeff11(7);

      

   
   mul_c5(0) := delay_pipeline_type_10(4) and coeff11(0);
   mul_c5(1) := delay_pipeline_type_10(4) and coeff11(1);
   mul_c5(2) := delay_pipeline_type_10(4) and coeff11(2);
   mul_c5(3) := delay_pipeline_type_10(4) and coeff11(3);
   mul_c5(4) := delay_pipeline_type_10(4) and coeff11(4);
   mul_c5(5) := delay_pipeline_type_10(4) and coeff11(5);
   mul_c5(6) := delay_pipeline_type_10(4) and coeff11(6);
   mul_c5(7) := delay_pipeline_type_10(4) and coeff11(7);
   mul_c5(8) := '0';

   mul_c6(0) := '0';
   mul_c6(1) := delay_pipeline_type_10(5) and coeff11(0);
   mul_c6(2) := delay_pipeline_type_10(5) and coeff11(1);
   mul_c6(3) := delay_pipeline_type_10(5) and coeff11(2);
   mul_c6(4) := delay_pipeline_type_10(5) and coeff11(3);
   mul_c6(5) := delay_pipeline_type_10(5) and coeff11(4);
   mul_c6(6) := delay_pipeline_type_10(5) and coeff11(5);
   mul_c6(7) := delay_pipeline_type_10(5) and coeff11(6);
   mul_c6(8) := delay_pipeline_type_10(5) and coeff11(7);

   mul_c7(0) := delay_pipeline_type_10(6) and coeff11(0);
   mul_c7(1) := delay_pipeline_type_10(6) and coeff11(1);
   mul_c7(2) := delay_pipeline_type_10(6) and coeff11(2);
   mul_c7(3) := delay_pipeline_type_10(6) and coeff11(3);
   mul_c7(4) := delay_pipeline_type_10(6) and coeff11(4);
   mul_c7(5) := delay_pipeline_type_10(6) and coeff11(5);
   mul_c7(6) := delay_pipeline_type_10(6) and coeff11(6);
   mul_c7(7) := delay_pipeline_type_10(6) and coeff11(7);
   mul_c7(8) := '0';

   mul_c8(0) := '0';
   mul_c8(1) := delay_pipeline_type_10(7) and coeff11(0);
   mul_c8(2) := delay_pipeline_type_10(7) and coeff11(1);
   mul_c8(3) := delay_pipeline_type_10(7) and coeff11(2);
   mul_c8(4) := delay_pipeline_type_10(7) and coeff11(3);
   mul_c8(5) := delay_pipeline_type_10(7) and coeff11(4);
   mul_c8(6) := delay_pipeline_type_10(7) and coeff11(5);
   mul_c8(7) := delay_pipeline_type_10(7) and coeff11(6);
   mul_c8(8) := delay_pipeline_type_10(7) and coeff11(7);


   mul_c12 := mul_c1 + mul_c2;
   mul_c34 := mul_c3 + mul_c4;
   mul_c56 := mul_c5 + mul_c6;
   mul_c78 := mul_c7 + mul_c8;

   add5 := ("00" & mul_c12) + (mul_c34 & "00");
   add6 := ("00" & mul_c56) + (mul_c78 & "00");
 
-----------------------------------------------------------
  mul_temp_2 <= add5 + add6;
  product11 <= mul_temp_2(12 DOWNTO 0);
-----------------------------------------------------------
   mul_d1(0) := delay_pipeline_type_9(0) and  coeff10(0);
   mul_d1(1) := delay_pipeline_type_9(0) and  coeff10(1);
   mul_d1(2) := delay_pipeline_type_9(0) and  coeff10(2);
   mul_d1(3) := delay_pipeline_type_9(0) and  coeff10(3);
   mul_d1(4) := delay_pipeline_type_9(0) and  coeff10(4);
   mul_d1(5) := delay_pipeline_type_9(0) and  coeff10(5);
   mul_d1(6) := delay_pipeline_type_9(0) and  coeff10(6);
   mul_d1(7) := delay_pipeline_type_9(0) and  coeff10(7);
   mul_d1(8) := '0';

   mul_d2(0) := '0';
   mul_d2(1) := delay_pipeline_type_9(1) and coeff10(0);
   mul_d2(2) := delay_pipeline_type_9(1) and coeff10(1);
   mul_d2(3) := delay_pipeline_type_9(1) and coeff10(2);
   mul_d2(4) := delay_pipeline_type_9(1) and coeff10(3);
   mul_d2(5) := delay_pipeline_type_9(1) and coeff10(4);
   mul_d2(6) := delay_pipeline_type_9(1) and coeff10(5);
   mul_d2(7) := delay_pipeline_type_9(1) and coeff10(6);
   mul_d2(8) := delay_pipeline_type_9(1) and coeff10(7);
   
   mul_d3(0) := delay_pipeline_type_9(2) and coeff10(0);
   mul_d3(1) := delay_pipeline_type_9(2) and coeff10(1);
   mul_d3(2) := delay_pipeline_type_9(2) and coeff10(2);
   mul_d3(3) := delay_pipeline_type_9(2) and coeff10(3);
   mul_d3(4) := delay_pipeline_type_9(2) and coeff10(4);
   mul_d3(5) := delay_pipeline_type_9(2) and coeff10(5);
   mul_d3(6) := delay_pipeline_type_9(2) and coeff10(6);
   mul_d3(7) := delay_pipeline_type_9(2) and coeff10(7);
   mul_d3(8) := '0';
   
   mul_d4(0) := '0';
   mul_d4(1) := delay_pipeline_type_9(3) and coeff10(0);
   mul_d4(2) := delay_pipeline_type_9(3) and coeff10(1);
   mul_d4(3) := delay_pipeline_type_9(3) and coeff10(2);
   mul_d4(4) := delay_pipeline_type_9(3) and coeff10(3);
   mul_d4(5) := delay_pipeline_type_9(3) and coeff10(4);
   mul_d4(6) := delay_pipeline_type_9(3) and coeff10(5);
   mul_d4(7) := delay_pipeline_type_9(3) and coeff10(6);
   mul_d4(8) := delay_pipeline_type_9(3) and coeff10(7);

   mul_d5(0) := delay_pipeline_type_9(4) and coeff10(0);
   mul_d5(1) := delay_pipeline_type_9(4) and coeff10(1);
   mul_d5(2) := delay_pipeline_type_9(4) and coeff10(2);
   mul_d5(3) := delay_pipeline_type_9(4) and coeff10(3);
   mul_d5(4) := delay_pipeline_type_9(4) and coeff10(4);
   mul_d5(5) := delay_pipeline_type_9(4) and coeff10(5);
   mul_d5(6) := delay_pipeline_type_9(4) and coeff10(6);
   mul_d5(7) := delay_pipeline_type_9(4) and coeff10(7);
   mul_d5(8) := '0';

   mul_d6(0) := '0';
   mul_d6(1) := delay_pipeline_type_9(5) and coeff10(0);
   mul_d6(2) := delay_pipeline_type_9(5) and coeff10(1);
   mul_d6(3) := delay_pipeline_type_9(5) and coeff10(2);
   mul_d6(4) := delay_pipeline_type_9(5) and coeff10(3);
   mul_d6(5) := delay_pipeline_type_9(5) and coeff10(4);
   mul_d6(6) := delay_pipeline_type_9(5) and coeff10(5);
   mul_d6(7) := delay_pipeline_type_9(5) and coeff10(6);
   mul_d6(8) := delay_pipeline_type_9(5) and coeff10(7);

   mul_d7(0) := delay_pipeline_type_9(6) and coeff10(0);
   mul_d7(1) := delay_pipeline_type_9(6) and coeff10(1);
   mul_d7(2) := delay_pipeline_type_9(6) and coeff10(2);
   mul_d7(3) := delay_pipeline_type_9(6) and coeff10(3);
   mul_d7(4) := delay_pipeline_type_9(6) and coeff10(4);
   mul_d7(5) := delay_pipeline_type_9(6) and coeff10(5);
   mul_d7(6) := delay_pipeline_type_9(6) and coeff10(6);
   mul_d7(7) := delay_pipeline_type_9(6) and coeff10(7);
   mul_d7(8) := '0';

   mul_d8(0) := '0';
   mul_d8(1) := delay_pipeline_type_9(7) and coeff10(0);
   mul_d8(2) := delay_pipeline_type_9(7) and coeff10(1);
   mul_d8(3) := delay_pipeline_type_9(7) and coeff10(2);
   mul_d8(4) := delay_pipeline_type_9(7) and coeff10(3);
   mul_d8(5) := delay_pipeline_type_9(7) and coeff10(4);
   mul_d8(6) := delay_pipeline_type_9(7) and coeff10(5);
   mul_d8(7) := delay_pipeline_type_9(7) and coeff10(6);
   mul_d8(8) := delay_pipeline_type_9(7) and coeff10(7);


   mul_d12 := mul_d1 + mul_d2;
   mul_d34 := mul_d3 + mul_d4;
   mul_d56 := mul_d5 + mul_d6;
   mul_d78 := mul_d7 + mul_d8;

   add7 := ("00" & mul_d12) + (mul_d34 & "00");
   add8 := ("00" & mul_d56) + (mul_d78 & "00");
-----------------------------------------------------------

  mul_temp_3 <= add7 + add8;
  product10 <= mul_temp_3(12 DOWNTO 0);
-----------------------------------------------------------

   mul_e1(0) := delay_pipeline_type_8(0) and  coeff9(0);
   mul_e1(1) := delay_pipeline_type_8(0) and  coeff9(1);
   mul_e1(2) := delay_pipeline_type_8(0) and  coeff9(2);
   mul_e1(3) := delay_pipeline_type_8(0) and  coeff9(3);
   mul_e1(4) := delay_pipeline_type_8(0) and  coeff9(4);
   mul_e1(5) := delay_pipeline_type_8(0) and  coeff9(5);
   mul_e1(6) := delay_pipeline_type_8(0) and  coeff9(6);
   mul_e1(7) := delay_pipeline_type_8(0) and  coeff9(7);
   mul_e1(8) := '0';

   mul_e2(0) := '0';
   mul_e2(1) := delay_pipeline_type_8(1) and coeff9(0);
   mul_e2(2) := delay_pipeline_type_8(1) and coeff9(1);
   mul_e2(3) := delay_pipeline_type_8(1) and coeff9(2);
   mul_e2(4) := delay_pipeline_type_8(1) and coeff9(3);
   mul_e2(5) := delay_pipeline_type_8(1) and coeff9(4);
   mul_e2(6) := delay_pipeline_type_8(1) and coeff9(5);
   mul_e2(7) := delay_pipeline_type_8(1) and coeff9(6);
   mul_e2(8) := delay_pipeline_type_8(1) and coeff9(7);
   
   mul_e3(0) := delay_pipeline_type_8(2) and coeff9(0);
   mul_e3(1) := delay_pipeline_type_8(2) and coeff9(1);
   mul_e3(2) := delay_pipeline_type_8(2) and coeff9(2);
   mul_e3(3) := delay_pipeline_type_8(2) and coeff9(3);
   mul_e3(4) := delay_pipeline_type_8(2) and coeff9(4);
   mul_e3(5) := delay_pipeline_type_8(2) and coeff9(5);
   mul_e3(6) := delay_pipeline_type_8(2) and coeff9(6);
   mul_e3(7) := delay_pipeline_type_8(2) and coeff9(7);
   mul_e3(8) := '0';
   
   mul_e4(0) := '0';
   mul_e4(1) := delay_pipeline_type_8(3) and coeff9(0);
   mul_e4(2) := delay_pipeline_type_8(3) and coeff9(1);
   mul_e4(3) := delay_pipeline_type_8(3) and coeff9(2);
   mul_e4(4) := delay_pipeline_type_8(3) and coeff9(3);
   mul_e4(5) := delay_pipeline_type_8(3) and coeff9(4);
   mul_e4(6) := delay_pipeline_type_8(3) and coeff9(5);
   mul_e4(7) := delay_pipeline_type_8(3) and coeff9(6);
   mul_e4(8) := delay_pipeline_type_8(3) and coeff9(7);

      

   
   mul_e5(0) := delay_pipeline_type_8(4) and coeff9(0);
   mul_e5(1) := delay_pipeline_type_8(4) and coeff9(1);
   mul_e5(2) := delay_pipeline_type_8(4) and coeff9(2);
   mul_e5(3) := delay_pipeline_type_8(4) and coeff9(3);
   mul_e5(4) := delay_pipeline_type_8(4) and coeff9(4);
   mul_e5(5) := delay_pipeline_type_8(4) and coeff9(5);
   mul_e5(6) := delay_pipeline_type_8(4) and coeff9(6);
   mul_e5(7) := delay_pipeline_type_8(4) and coeff9(7);
   mul_e5(8) := '0';

   mul_e6(0) := '0';
   mul_e6(1) := delay_pipeline_type_8(5) and coeff9(0);
   mul_e6(2) := delay_pipeline_type_8(5) and coeff9(1);
   mul_e6(3) := delay_pipeline_type_8(5) and coeff9(2);
   mul_e6(4) := delay_pipeline_type_8(5) and coeff9(3);
   mul_e6(5) := delay_pipeline_type_8(5) and coeff9(4);
   mul_e6(6) := delay_pipeline_type_8(5) and coeff9(5);
   mul_e6(7) := delay_pipeline_type_8(5) and coeff9(6);
   mul_e6(8) := delay_pipeline_type_8(5) and coeff9(7);

   mul_e7(0) := delay_pipeline_type_8(6) and coeff9(0);
   mul_e7(1) := delay_pipeline_type_8(6) and coeff9(1);
   mul_e7(2) := delay_pipeline_type_8(6) and coeff9(2);
   mul_e7(3) := delay_pipeline_type_8(6) and coeff9(3);
   mul_e7(4) := delay_pipeline_type_8(6) and coeff9(4);
   mul_e7(5) := delay_pipeline_type_8(6) and coeff9(5);
   mul_e7(6) := delay_pipeline_type_8(6) and coeff9(6);
   mul_e7(7) := delay_pipeline_type_8(6) and coeff9(7);
   mul_e7(8) := '0';

   mul_e8(0) := '0';
   mul_e8(1) := delay_pipeline_type_8(7) and coeff9(0);
   mul_e8(2) := delay_pipeline_type_8(7) and coeff9(1);
   mul_e8(3) := delay_pipeline_type_8(7) and coeff9(2);
   mul_e8(4) := delay_pipeline_type_8(7) and coeff9(3);
   mul_e8(5) := delay_pipeline_type_8(7) and coeff9(4);
   mul_e8(6) := delay_pipeline_type_8(7) and coeff9(5);
   mul_e8(7) := delay_pipeline_type_8(7) and coeff9(6);
   mul_e8(8) := delay_pipeline_type_8(7) and coeff9(7);


   mul_e12 := mul_e1 + mul_e2;
   mul_e34 := mul_e3 + mul_e4;
   mul_e56 := mul_e5 + mul_e6;
   mul_e78 := mul_e7 + mul_e8;

   add9 := ("00" & mul_e12) + (mul_e34 & "00");
   add10 := ("00" & mul_e56) + (mul_e78 & "00");
-----------------------------------------------------------

  mul_temp_4 <= add9 + add10;
  product9 <= mul_temp_4(12 DOWNTO 0);
-----------------------------------------------------------
    mul_f1(0) := delay_pipeline_type_7(0) and  coeff8(0);
   mul_f1(1) := delay_pipeline_type_7(0) and  coeff8(1);
   mul_f1(2) := delay_pipeline_type_7(0) and  coeff8(2);
   mul_f1(3) := delay_pipeline_type_7(0) and  coeff8(3);
   mul_f1(4) := delay_pipeline_type_7(0) and  coeff8(4);
   mul_f1(5) := delay_pipeline_type_7(0) and  coeff8(5);
   mul_f1(6) := delay_pipeline_type_7(0) and  coeff8(6);
   mul_f1(7) := delay_pipeline_type_7(0) and  coeff8(7);
   mul_f1(8) := '0';

   mul_f2(0) := '0';
   mul_f2(1) := delay_pipeline_type_7(1) and coeff8(0);
   mul_f2(2) := delay_pipeline_type_7(1) and coeff8(1);
   mul_f2(3) := delay_pipeline_type_7(1) and coeff8(2);
   mul_f2(4) := delay_pipeline_type_7(1) and coeff8(3);
   mul_f2(5) := delay_pipeline_type_7(1) and coeff8(4);
   mul_f2(6) := delay_pipeline_type_7(1) and coeff8(5);
   mul_f2(7) := delay_pipeline_type_7(1) and coeff8(6);
   mul_f2(8) := delay_pipeline_type_7(1) and coeff8(7);
   
   mul_f3(0) := delay_pipeline_type_7(2) and coeff8(0);
   mul_f3(1) := delay_pipeline_type_7(2) and coeff8(1);
   mul_f3(2) := delay_pipeline_type_7(2) and coeff8(2);
   mul_f3(3) := delay_pipeline_type_7(2) and coeff8(3);
   mul_f3(4) := delay_pipeline_type_7(2) and coeff8(4);
   mul_f3(5) := delay_pipeline_type_7(2) and coeff8(5);
   mul_f3(6) := delay_pipeline_type_7(2) and coeff8(6);
   mul_f3(7) := delay_pipeline_type_7(2) and coeff8(7);
   mul_f3(8) := '0';
   
   mul_f4(0) := '0';
   mul_f4(1) := delay_pipeline_type_7(3) and coeff8(0);
   mul_f4(2) := delay_pipeline_type_7(3) and coeff8(1);
   mul_f4(3) := delay_pipeline_type_7(3) and coeff8(2);
   mul_f4(4) := delay_pipeline_type_7(3) and coeff8(3);
   mul_f4(5) := delay_pipeline_type_7(3) and coeff8(4);
   mul_f4(6) := delay_pipeline_type_7(3) and coeff8(5);
   mul_f4(7) := delay_pipeline_type_7(3) and coeff8(6);
   mul_f4(8) := delay_pipeline_type_7(3) and coeff8(7);

   mul_f5(0) := delay_pipeline_type_7(4) and coeff8(0);
   mul_f5(1) := delay_pipeline_type_7(4) and coeff8(1);
   mul_f5(2) := delay_pipeline_type_7(4) and coeff8(2);
   mul_f5(3) := delay_pipeline_type_7(4) and coeff8(3);
   mul_f5(4) := delay_pipeline_type_7(4) and coeff8(4);
   mul_f5(5) := delay_pipeline_type_7(4) and coeff8(5);
   mul_f5(6) := delay_pipeline_type_7(4) and coeff8(6);
   mul_f5(7) := delay_pipeline_type_7(4) and coeff8(7);
   mul_f5(8) := '0';

   mul_f6(0) := '0';
   mul_f6(1) := delay_pipeline_type_7(5) and coeff8(0);
   mul_f6(2) := delay_pipeline_type_7(5) and coeff8(1);
   mul_f6(3) := delay_pipeline_type_7(5) and coeff8(2);
   mul_f6(4) := delay_pipeline_type_7(5) and coeff8(3);
   mul_f6(5) := delay_pipeline_type_7(5) and coeff8(4);
   mul_f6(6) := delay_pipeline_type_7(5) and coeff8(5);
   mul_f6(7) := delay_pipeline_type_7(5) and coeff8(6);
   mul_f6(8) := delay_pipeline_type_7(5) and coeff8(7);

   mul_f7(0) := delay_pipeline_type_7(6) and coeff8(0);
   mul_f7(1) := delay_pipeline_type_7(6) and coeff8(1);
   mul_f7(2) := delay_pipeline_type_7(6) and coeff8(2);
   mul_f7(3) := delay_pipeline_type_7(6) and coeff8(3);
   mul_f7(4) := delay_pipeline_type_7(6) and coeff8(4);
   mul_f7(5) := delay_pipeline_type_7(6) and coeff8(5);
   mul_f7(6) := delay_pipeline_type_7(6) and coeff8(6);
   mul_f7(7) := delay_pipeline_type_7(6) and coeff8(7);
   mul_f7(8) := '0';

   mul_f8(0) := '0';
   mul_f8(1) := delay_pipeline_type_7(7) and coeff8(0);
   mul_f8(2) := delay_pipeline_type_7(7) and coeff8(1);
   mul_f8(3) := delay_pipeline_type_7(7) and coeff8(2);
   mul_f8(4) := delay_pipeline_type_7(7) and coeff8(3);
   mul_f8(5) := delay_pipeline_type_7(7) and coeff8(4);
   mul_f8(6) := delay_pipeline_type_7(7) and coeff8(5);
   mul_f8(7) := delay_pipeline_type_7(7) and coeff8(6);
   mul_f8(8) := delay_pipeline_type_7(7) and coeff8(7);


   mul_f12 := mul_f1 + mul_f2;
   mul_f34 := mul_f3 + mul_f4;
   mul_f56 := mul_f5 + mul_f6;
   mul_f78 := mul_f7 + mul_f8;

   add11 := ("00" & mul_f12) + (mul_f34 & "00");
   add12 := ("00" & mul_f56) + (mul_f78 & "00");
-----------------------------------------------------------
  mul_temp_5 <= add11 + add12;
  product8 <= mul_temp_5(12 DOWNTO 0);
-----------------------------------------------------------

   mul_g1(0) := delay_pipeline_type_6(0) and  coeff7(0);
   mul_g1(1) := delay_pipeline_type_6(0) and  coeff7(1);
   mul_g1(2) := delay_pipeline_type_6(0) and  coeff7(2);
   mul_g1(3) := delay_pipeline_type_6(0) and  coeff7(3);
   mul_g1(4) := delay_pipeline_type_6(0) and  coeff7(4);
   mul_g1(5) := delay_pipeline_type_6(0) and  coeff7(5);
   mul_g1(6) := delay_pipeline_type_6(0) and  coeff7(6);
   mul_g1(7) := delay_pipeline_type_6(0) and  coeff7(7);
   mul_g1(8) := '0';

   mul_g2(0) := '0';
   mul_g2(1) := delay_pipeline_type_6(1) and coeff7(0);
   mul_g2(2) := delay_pipeline_type_6(1) and coeff7(1);
   mul_g2(3) := delay_pipeline_type_6(1) and coeff7(2);
   mul_g2(4) := delay_pipeline_type_6(1) and coeff7(3);
   mul_g2(5) := delay_pipeline_type_6(1) and coeff7(4);
   mul_g2(6) := delay_pipeline_type_6(1) and coeff7(5);
   mul_g2(7) := delay_pipeline_type_6(1) and coeff7(6);
   mul_g2(8) := delay_pipeline_type_6(1) and coeff7(7);
   
   mul_g3(0) := delay_pipeline_type_6(2) and coeff7(0);
   mul_g3(1) := delay_pipeline_type_6(2) and coeff7(1);
   mul_g3(2) := delay_pipeline_type_6(2) and coeff7(2);
   mul_g3(3) := delay_pipeline_type_6(2) and coeff7(3);
   mul_g3(4) := delay_pipeline_type_6(2) and coeff7(4);
   mul_g3(5) := delay_pipeline_type_6(2) and coeff7(5);
   mul_g3(6) := delay_pipeline_type_6(2) and coeff7(6);
   mul_g3(7) := delay_pipeline_type_6(2) and coeff7(7);
   mul_g3(8) := '0';
   
   mul_g4(0) := '0';
   mul_g4(1) := delay_pipeline_type_6(3) and coeff7(0);
   mul_g4(2) := delay_pipeline_type_6(3) and coeff7(1);
   mul_g4(3) := delay_pipeline_type_6(3) and coeff7(2);
   mul_g4(4) := delay_pipeline_type_6(3) and coeff7(3);
   mul_g4(5) := delay_pipeline_type_6(3) and coeff7(4);
   mul_g4(6) := delay_pipeline_type_6(3) and coeff7(5);
   mul_g4(7) := delay_pipeline_type_6(3) and coeff7(6);
   mul_g4(8) := delay_pipeline_type_6(3) and coeff7(7);

   mul_g5(0) := delay_pipeline_type_6(4) and coeff7(0);
   mul_g5(1) := delay_pipeline_type_6(4) and coeff7(1);
   mul_g5(2) := delay_pipeline_type_6(4) and coeff7(2);
   mul_g5(3) := delay_pipeline_type_6(4) and coeff7(3);
   mul_g5(4) := delay_pipeline_type_6(4) and coeff7(4);
   mul_g5(5) := delay_pipeline_type_6(4) and coeff7(5);
   mul_g5(6) := delay_pipeline_type_6(4) and coeff7(6);
   mul_g5(7) := delay_pipeline_type_6(4) and coeff7(7);
   mul_g5(8) := '0';

   mul_g6(0) := '0';
   mul_g6(1) := delay_pipeline_type_6(5) and coeff7(0);
   mul_g6(2) := delay_pipeline_type_6(5) and coeff7(1);
   mul_g6(3) := delay_pipeline_type_6(5) and coeff7(2);
   mul_g6(4) := delay_pipeline_type_6(5) and coeff7(3);
   mul_g6(5) := delay_pipeline_type_6(5) and coeff7(4);
   mul_g6(6) := delay_pipeline_type_6(5) and coeff7(5);
   mul_g6(7) := delay_pipeline_type_6(5) and coeff7(6);
   mul_g6(8) := delay_pipeline_type_6(5) and coeff7(7);

   mul_g7(0) := delay_pipeline_type_6(6) and coeff7(0);
   mul_g7(1) := delay_pipeline_type_6(6) and coeff7(1);
   mul_g7(2) := delay_pipeline_type_6(6) and coeff7(2);
   mul_g7(3) := delay_pipeline_type_6(6) and coeff7(3);
   mul_g7(4) := delay_pipeline_type_6(6) and coeff7(4);
   mul_g7(5) := delay_pipeline_type_6(6) and coeff7(5);
   mul_g7(6) := delay_pipeline_type_6(6) and coeff7(6);
   mul_g7(7) := delay_pipeline_type_6(6) and coeff7(7);
   mul_g7(8) := '0';

   mul_g8(0) := '0';
   mul_g8(1) := delay_pipeline_type_6(7) and coeff7(0);
   mul_g8(2) := delay_pipeline_type_6(7) and coeff7(1);
   mul_g8(3) := delay_pipeline_type_6(7) and coeff7(2);
   mul_g8(4) := delay_pipeline_type_6(7) and coeff7(3);
   mul_g8(5) := delay_pipeline_type_6(7) and coeff7(4);
   mul_g8(6) := delay_pipeline_type_6(7) and coeff7(5);
   mul_g8(7) := delay_pipeline_type_6(7) and coeff7(6);
   mul_g8(8) := delay_pipeline_type_6(7) and coeff7(7);


   mul_g12 := mul_g1 + mul_g2;
   mul_g34 := mul_g3 + mul_g4;
   mul_g56 := mul_g5 + mul_g6;
   mul_g78 := mul_g7 + mul_g8;

   add13 := ("00" & mul_g12) + (mul_g34 & "00");
   add14 := ("00" & mul_g56) + (mul_g78 & "00");
 
-----------------------------------------------------------

  mul_temp_6 <= add13 + add14;
  product7 <= mul_temp_6(12 DOWNTO 0);
-----------------------------------------------------------

   mul_h1(0) := delay_pipeline_type_5(0) and  coeff6(0);
   mul_h1(1) := delay_pipeline_type_5(0) and  coeff6(1);
   mul_h1(2) := delay_pipeline_type_5(0) and  coeff6(2);
   mul_h1(3) := delay_pipeline_type_5(0) and  coeff6(3);
   mul_h1(4) := delay_pipeline_type_5(0) and  coeff6(4);
   mul_h1(5) := delay_pipeline_type_5(0) and  coeff6(5);
   mul_h1(6) := delay_pipeline_type_5(0) and  coeff6(6);
   mul_h1(7) := delay_pipeline_type_5(0) and  coeff6(7);
   mul_h1(8) := '0';

   mul_h2(0) := '0';
   mul_h2(1) := delay_pipeline_type_5(1) and coeff6(0);
   mul_h2(2) := delay_pipeline_type_5(1) and coeff6(1);
   mul_h2(3) := delay_pipeline_type_5(1) and coeff6(2);
   mul_h2(4) := delay_pipeline_type_5(1) and coeff6(3);
   mul_h2(5) := delay_pipeline_type_5(1) and coeff6(4);
   mul_h2(6) := delay_pipeline_type_5(1) and coeff6(5);
   mul_h2(7) := delay_pipeline_type_5(1) and coeff6(6);
   mul_h2(8) := delay_pipeline_type_5(1) and coeff6(7);
   
   mul_h3(0) := delay_pipeline_type_5(2) and coeff6(0);
   mul_h3(1) := delay_pipeline_type_5(2) and coeff6(1);
   mul_h3(2) := delay_pipeline_type_5(2) and coeff6(2);
   mul_h3(3) := delay_pipeline_type_5(2) and coeff6(3);
   mul_h3(4) := delay_pipeline_type_5(2) and coeff6(4);
   mul_h3(5) := delay_pipeline_type_5(2) and coeff6(5);
   mul_h3(6) := delay_pipeline_type_5(2) and coeff6(6);
   mul_h3(7) := delay_pipeline_type_5(2) and coeff6(7);
   mul_h3(8) := '0';
   
   mul_h4(0) := '0';
   mul_h4(1) := delay_pipeline_type_5(3) and coeff6(0);
   mul_h4(2) := delay_pipeline_type_5(3) and coeff6(1);
   mul_h4(3) := delay_pipeline_type_5(3) and coeff6(2);
   mul_h4(4) := delay_pipeline_type_5(3) and coeff6(3);
   mul_h4(5) := delay_pipeline_type_5(3) and coeff6(4);
   mul_h4(6) := delay_pipeline_type_5(3) and coeff6(5);
   mul_h4(7) := delay_pipeline_type_5(3) and coeff6(6);
   mul_h4(8) := delay_pipeline_type_5(3) and coeff6(7);
   
   mul_h5(0) := delay_pipeline_type_5(4) and coeff6(0);
   mul_h5(1) := delay_pipeline_type_5(4) and coeff6(1);
   mul_h5(2) := delay_pipeline_type_5(4) and coeff6(2);
   mul_h5(3) := delay_pipeline_type_5(4) and coeff6(3);
   mul_h5(4) := delay_pipeline_type_5(4) and coeff6(4);
   mul_h5(5) := delay_pipeline_type_5(4) and coeff6(5);
   mul_h5(6) := delay_pipeline_type_5(4) and coeff6(6);
   mul_h5(7) := delay_pipeline_type_5(4) and coeff6(7);
   mul_h5(8) := '0';

   mul_h6(0) := '0';
   mul_h6(1) := delay_pipeline_type_5(5) and coeff6(0);
   mul_h6(2) := delay_pipeline_type_5(5) and coeff6(1);
   mul_h6(3) := delay_pipeline_type_5(5) and coeff6(2);
   mul_h6(4) := delay_pipeline_type_5(5) and coeff6(3);
   mul_h6(5) := delay_pipeline_type_5(5) and coeff6(4);
   mul_h6(6) := delay_pipeline_type_5(5) and coeff6(5);
   mul_h6(7) := delay_pipeline_type_5(5) and coeff6(6);
   mul_h6(8) := delay_pipeline_type_5(5) and coeff6(7);

   mul_h7(0) := delay_pipeline_type_5(6) and coeff6(0);
   mul_h7(1) := delay_pipeline_type_5(6) and coeff6(1);
   mul_h7(2) := delay_pipeline_type_5(6) and coeff6(2);
   mul_h7(3) := delay_pipeline_type_5(6) and coeff6(3);
   mul_h7(4) := delay_pipeline_type_5(6) and coeff6(4);
   mul_h7(5) := delay_pipeline_type_5(6) and coeff6(5);
   mul_h7(6) := delay_pipeline_type_5(6) and coeff6(6);
   mul_h7(7) := delay_pipeline_type_5(6) and coeff6(7);
   mul_h7(8) := '0';

   mul_h8(0) := '0';
   mul_h8(1) := delay_pipeline_type_5(7) and coeff6(0);
   mul_h8(2) := delay_pipeline_type_5(7) and coeff6(1);
   mul_h8(3) := delay_pipeline_type_5(7) and coeff6(2);
   mul_h8(4) := delay_pipeline_type_5(7) and coeff6(3);
   mul_h8(5) := delay_pipeline_type_5(7) and coeff6(4);
   mul_h8(6) := delay_pipeline_type_5(7) and coeff6(5);
   mul_h8(7) := delay_pipeline_type_5(7) and coeff6(6);
   mul_h8(8) := delay_pipeline_type_5(7) and coeff6(7);


   mul_h12 := mul_h1 + mul_h2;
   mul_h34 := mul_h3 + mul_h4;
   mul_h56 := mul_h5 + mul_h6;
   mul_h78 := mul_h7 + mul_h8;

   add15 := ("00" & mul_h12) + (mul_h34 & "00");
   add16 := ("00" & mul_h56) + (mul_h78 & "00");

-----------------------------------------------------------

  mul_temp_7 <= add15 + add16;
  product6 <= mul_temp_7(12 DOWNTO 0);
-----------------------------------------------------------

  product5 <= resize(delay_pipeline_type_4(15 DOWNTO 0) , 15);

  product4 <= resize(delay_pipeline_type_3(15 DOWNTO 0) ,  15);

  product3 <= resize(delay_pipeline_type_2, 15);
-----------------------------------------------------------
   mul_i1(0) := delay_pipeline_type_1(0) and  coeff2(0);
   mul_i1(1) := delay_pipeline_type_1(0) and  coeff2(1);
   mul_i1(2) := delay_pipeline_type_1(0) and  coeff2(2);
   mul_i1(3) := delay_pipeline_type_1(0) and  coeff2(3);
   mul_i1(4) := delay_pipeline_type_1(0) and  coeff2(4);
   mul_i1(5) := delay_pipeline_type_1(0) and  coeff2(5);
   mul_i1(6) := delay_pipeline_type_1(0) and  coeff2(6);
   mul_i1(7) := delay_pipeline_type_1(0) and  coeff2(7);
   mul_i1(8) := '0';

   mul_i2(0) := '0';
   mul_i2(1) := delay_pipeline_type_1(1) and coeff2(0);
   mul_i2(2) := delay_pipeline_type_1(1) and coeff2(1);
   mul_i2(3) := delay_pipeline_type_1(1) and coeff2(2);
   mul_i2(4) := delay_pipeline_type_1(1) and coeff2(3);
   mul_i2(5) := delay_pipeline_type_1(1) and coeff2(4);
   mul_i2(6) := delay_pipeline_type_1(1) and coeff2(5);
   mul_i2(7) := delay_pipeline_type_1(1) and coeff2(6);
   mul_i2(8) := delay_pipeline_type_1(1) and coeff2(7);
   
   mul_i3(0) := delay_pipeline_type_1(2) and coeff2(0);
   mul_i3(1) := delay_pipeline_type_1(2) and coeff2(1);
   mul_i3(2) := delay_pipeline_type_1(2) and coeff2(2);
   mul_i3(3) := delay_pipeline_type_1(2) and coeff2(3);
   mul_i3(4) := delay_pipeline_type_1(2) and coeff2(4);
   mul_i3(5) := delay_pipeline_type_1(2) and coeff2(5);
   mul_i3(6) := delay_pipeline_type_1(2) and coeff2(6);
   mul_i3(7) := delay_pipeline_type_1(2) and coeff2(7);
   mul_i3(8) := '0';
   
   mul_i4(0) := '0';
   mul_i4(1) := delay_pipeline_type_1(3) and coeff2(0);
   mul_i4(2) := delay_pipeline_type_1(3) and coeff2(1);
   mul_i4(3) := delay_pipeline_type_1(3) and coeff2(2);
   mul_i4(4) := delay_pipeline_type_1(3) and coeff2(3);
   mul_i4(5) := delay_pipeline_type_1(3) and coeff2(4);
   mul_i4(6) := delay_pipeline_type_1(3) and coeff2(5);
   mul_i4(7) := delay_pipeline_type_1(3) and coeff2(6);
   mul_i4(8) := delay_pipeline_type_1(3) and coeff2(7);

   mul_i5(0) := delay_pipeline_type_1(4) and coeff2(0);
   mul_i5(1) := delay_pipeline_type_1(4) and coeff2(1);
   mul_i5(2) := delay_pipeline_type_1(4) and coeff2(2);
   mul_i5(3) := delay_pipeline_type_1(4) and coeff2(3);
   mul_i5(4) := delay_pipeline_type_1(4) and coeff2(4);
   mul_i5(5) := delay_pipeline_type_1(4) and coeff2(5);
   mul_i5(6) := delay_pipeline_type_1(4) and coeff2(6);
   mul_i5(7) := delay_pipeline_type_1(4) and coeff2(7);
   mul_i5(8) := '0';

   mul_i6(0) := '0';
   mul_i6(1) := delay_pipeline_type_1(5) and coeff2(0);
   mul_i6(2) := delay_pipeline_type_1(5) and coeff2(1);
   mul_i6(3) := delay_pipeline_type_1(5) and coeff2(2);
   mul_i6(4) := delay_pipeline_type_1(5) and coeff2(3);
   mul_i6(5) := delay_pipeline_type_1(5) and coeff2(4);
   mul_i6(6) := delay_pipeline_type_1(5) and coeff2(5);
   mul_i6(7) := delay_pipeline_type_1(5) and coeff2(6);
   mul_i6(8) := delay_pipeline_type_1(5) and coeff2(7);

   mul_i7(0) := delay_pipeline_type_1(6) and coeff2(0);
   mul_i7(1) := delay_pipeline_type_1(6) and coeff2(1);
   mul_i7(2) := delay_pipeline_type_1(6) and coeff2(2);
   mul_i7(3) := delay_pipeline_type_1(6) and coeff2(3);
   mul_i7(4) := delay_pipeline_type_1(6) and coeff2(4);
   mul_i7(5) := delay_pipeline_type_1(6) and coeff2(5);
   mul_i7(6) := delay_pipeline_type_1(6) and coeff2(6);
   mul_i7(7) := delay_pipeline_type_1(6) and coeff2(7);
   mul_i7(8) := '0';

   mul_i8(0) := '0';
   mul_i8(1) := delay_pipeline_type_1(7) and coeff2(0);
   mul_i8(2) := delay_pipeline_type_1(7) and coeff2(1);
   mul_i8(3) := delay_pipeline_type_1(7) and coeff2(2);
   mul_i8(4) := delay_pipeline_type_1(7) and coeff2(3);
   mul_i8(5) := delay_pipeline_type_1(7) and coeff2(4);
   mul_i8(6) := delay_pipeline_type_1(7) and coeff2(5);
   mul_i8(7) := delay_pipeline_type_1(7) and coeff2(6);
   mul_i8(8) := delay_pipeline_type_1(7) and coeff2(7);


   mul_i12 := mul_i1 + mul_i2;
   mul_i34 := mul_i3 + mul_i4;
   mul_i56 := mul_i5 + mul_i6;
   mul_i78 := mul_i7 + mul_i8;

   add17 := ("00" & mul_i12) + (mul_i34 & "00");
   add18 := ("00" & mul_i56) + (mul_i78 & "00");
 
-----------------------------------------------------------

  mul_temp_8 <= add17 + add18;
  product2 <= mul_temp_8(12 DOWNTO 0);
-----------------------------------------------------------

  product1_cast <= resize(product1, 16);
-----------------------------------------------------------
   mul_j1(0) := delay_pipeline_type_0(0) and  coeff1(0);
   mul_j1(1) := delay_pipeline_type_0(0) and  coeff1(1);
   mul_j1(2) := delay_pipeline_type_0(0) and  coeff1(2);
   mul_j1(3) := delay_pipeline_type_0(0) and  coeff1(3);
   mul_j1(4) := delay_pipeline_type_0(0) and  coeff1(4);
   mul_j1(5) := delay_pipeline_type_0(0) and  coeff1(5);
   mul_j1(6) := delay_pipeline_type_0(0) and  coeff1(6);
   mul_j1(7) := delay_pipeline_type_0(0) and  coeff1(7);
   mul_j1(8) := '0';

   mul_j2(0) := '0';
   mul_j2(1) := delay_pipeline_type_0(1) and coeff1(0);
   mul_j2(2) := delay_pipeline_type_0(1) and coeff1(1);
   mul_j2(3) := delay_pipeline_type_0(1) and coeff1(2);
   mul_j2(4) := delay_pipeline_type_0(1) and coeff1(3);
   mul_j2(5) := delay_pipeline_type_0(1) and coeff1(4);
   mul_j2(6) := delay_pipeline_type_0(1) and coeff1(5);
   mul_j2(7) := delay_pipeline_type_0(1) and coeff1(6);
   mul_j2(8) := delay_pipeline_type_0(1) and coeff1(7);
   
   mul_j3(0) := delay_pipeline_type_0(2) and coeff1(0);
   mul_j3(1) := delay_pipeline_type_0(2) and coeff1(1);
   mul_j3(2) := delay_pipeline_type_0(2) and coeff1(2);
   mul_j3(3) := delay_pipeline_type_0(2) and coeff1(3);
   mul_j3(4) := delay_pipeline_type_0(2) and coeff1(4);
   mul_j3(5) := delay_pipeline_type_0(2) and coeff1(5);
   mul_j3(6) := delay_pipeline_type_0(2) and coeff1(6);
   mul_j3(7) := delay_pipeline_type_0(2) and coeff1(7);
   mul_j3(8) := '0';
   
   mul_j4(0) := '0';
   mul_j4(1) := delay_pipeline_type_0(3) and coeff1(0);
   mul_j4(2) := delay_pipeline_type_0(3) and coeff1(1);
   mul_j4(3) := delay_pipeline_type_0(3) and coeff1(2);
   mul_j4(4) := delay_pipeline_type_0(3) and coeff1(3);
   mul_j4(5) := delay_pipeline_type_0(3) and coeff1(4);
   mul_j4(6) := delay_pipeline_type_0(3) and coeff1(5);
   mul_j4(7) := delay_pipeline_type_0(3) and coeff1(6);
   mul_j4(8) := delay_pipeline_type_0(3) and coeff1(7);

   mul_j5(0) := delay_pipeline_type_0(4) and coeff1(0);
   mul_j5(1) := delay_pipeline_type_0(4) and coeff1(1);
   mul_j5(2) := delay_pipeline_type_0(4) and coeff1(2);
   mul_j5(3) := delay_pipeline_type_0(4) and coeff1(3);
   mul_j5(4) := delay_pipeline_type_0(4) and coeff1(4);
   mul_j5(5) := delay_pipeline_type_0(4) and coeff1(5);
   mul_j5(6) := delay_pipeline_type_0(4) and coeff1(6);
   mul_j5(7) := delay_pipeline_type_0(4) and coeff1(7);
   mul_j5(8) := '0';

   mul_j6(0) := '0';
   mul_j6(1) := delay_pipeline_type_0(5) and coeff1(0);
   mul_j6(2) := delay_pipeline_type_0(5) and coeff1(1);
   mul_j6(3) := delay_pipeline_type_0(5) and coeff1(2);
   mul_j6(4) := delay_pipeline_type_0(5) and coeff1(3);
   mul_j6(5) := delay_pipeline_type_0(5) and coeff1(4);
   mul_j6(6) := delay_pipeline_type_0(5) and coeff1(5);
   mul_j6(7) := delay_pipeline_type_0(5) and coeff1(6);
   mul_j6(8) := delay_pipeline_type_0(5) and coeff1(7);

   mul_j7(0) := delay_pipeline_type_0(6) and coeff1(0);
   mul_j7(1) := delay_pipeline_type_0(6) and coeff1(1);
   mul_j7(2) := delay_pipeline_type_0(6) and coeff1(2);
   mul_j7(3) := delay_pipeline_type_0(6) and coeff1(3);
   mul_j7(4) := delay_pipeline_type_0(6) and coeff1(4);
   mul_j7(5) := delay_pipeline_type_0(6) and coeff1(5);
   mul_j7(6) := delay_pipeline_type_0(6) and coeff1(6);
   mul_j7(7) := delay_pipeline_type_0(6) and coeff1(7);
   mul_j7(8) := '0';

   mul_j8(0) := '0';
   mul_j8(1) := delay_pipeline_type_0(7) and coeff1(0);
   mul_j8(2) := delay_pipeline_type_0(7) and coeff1(1);
   mul_j8(3) := delay_pipeline_type_0(7) and coeff1(2);
   mul_j8(4) := delay_pipeline_type_0(7) and coeff1(3);
   mul_j8(5) := delay_pipeline_type_0(7) and coeff1(4);
   mul_j8(6) := delay_pipeline_type_0(7) and coeff1(5);
   mul_j8(7) := delay_pipeline_type_0(7) and coeff1(6);
   mul_j8(8) := delay_pipeline_type_0(7) and coeff1(7);


   mul_j12 := mul_j1 + mul_j2;
   mul_j34 := mul_j3 + mul_j4;
   mul_j56 := mul_j5 + mul_j6;
   mul_j78 := mul_j7 + mul_j8;

   add19 := ("00" & mul_j12) + (mul_j34 & "00");
   add20 := ("00" & mul_j56) + (mul_j78 & "00");
-----------------------------------------------------------

  mul_temp_9 <= add19 + add20;
  product1 <= mul_temp_9(12 DOWNTO 0);
-----------------------------------------------------------

  add_temp <= resize(product1_cast, 17) + resize(product2, 17);
  sum1 <= add_temp(15 DOWNTO 0);

  add_temp_1 <= resize(sum1, 17) + resize(product3, 17);
  sum2 <= add_temp_1(15 DOWNTO 0);

  add_temp_2 <= resize(sum2, 17) + resize(product4, 17);
  sum3 <= add_temp_2(15 DOWNTO 0);

  add_temp_3 <= resize(sum3, 17) + resize(product5, 17);
  sum4 <= add_temp_3(15 DOWNTO 0);

  add_temp_4 <= resize(sum4, 17) + resize(product6, 17);
  sum5 <= add_temp_4(15 DOWNTO 0);

  add_temp_5 <= resize(sum5, 17) + resize(product7, 17);
  sum6 <= add_temp_5(15 DOWNTO 0);

  add_temp_6 <= resize(sum6, 17) + resize(product8, 17);
  sum7 <= add_temp_6(15 DOWNTO 0);

  add_temp_7 <= resize(sum7, 17) + resize(product9, 17);
  sum8 <= add_temp_7(15 DOWNTO 0);

  add_temp_8 <= resize(sum8, 17) + resize(product10, 17);
  sum9 <= add_temp_8(15 DOWNTO 0);

  add_temp_9 <= resize(sum9, 17) + resize(product11, 17);
  sum10 <= add_temp_9(15 DOWNTO 0);

  add_temp_10 <= resize(sum10, 17) + resize(product12, 17);
  sum11 <= add_temp_10(15 DOWNTO 0);

  add_temp_11 <= resize(sum11, 17) + resize(product13, 17);
  sum12 <= add_temp_11(15 DOWNTO 0);

  add_temp_12 <= resize(sum12, 17) + resize(product14, 17);
  sum13 <= add_temp_12(15 DOWNTO 0);

  add_temp_13 <= resize(sum13, 17) + resize(product15, 17);
  sum14 <= add_temp_13(15 DOWNTO 0);

  add_temp_14 <= resize(sum14, 17) + resize(product16, 17);
  sum15 <= add_temp_14(15 DOWNTO 0);

  output_typeconvert <= sum15;

  
        output_register <= output_typeconvert;
      
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
